# Generated by Django 4.1.7 on 2023-08-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_likes_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short',
            field=models.TextField(default='NA'),
        ),
    ]
