# Generated by Django 4.1.7 on 2023-08-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(choices=[('Publish', True), ("Don't Pynlish", False)], default=True),
        ),
    ]
