# Generated by Django 4.1.7 on 2023-08-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_post_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(choices=[(True, 'Post'), (False, "Don't Post")], default=True),
        ),
    ]
